Mute and Stop Video
hummingbird-jp/stat-web pull request #204
Opened 2021-09-23 05:07 UTC by yhakamay

Add ability to mute and stop video.

2021-09-23 05:34 UTC, yhakamay commented
@RQ2L84Q-ROW オナシャス

2021-09-23 05:50 UTC, RQ2L84Q-ROW requested changes
@yhakamay  Looks Good!
マイクオフ／カメラオフにしたときにアイコンの画像も変えられたりする？

2021-09-23 06:55 UTC, yhakamay commented
@RQ2L84Q-ROW いける！けど、表現に悩むところ。トグルボタンでカメラ/マイクのオン・オフを示すのが良さげなので、テスト実装してます 🙆‍♂️

2021-09-23 11:05 UTC, yhakamay commented
@RQ2L84Q-ROW こんな感じでどうかな？真ん中に置くのは異物感強かったので、Aroundを見習って左に寄せてみた！
![image](https://user-images.githubusercontent.com/65002858/134496601-e81a6a7a-816d-4f65-94d8-0f268d30e269.png)

2021-09-23 14:58 UTC, yhakamay commented
@RQ2L84Q-ROW お願いします！

2021-09-24 00:37 UTC, RQ2L84Q-ROW approved these changes
Great Work!

2021-09-24 00:38 UTC, merged