Start Menu UI improvements (orders, colors and tooltips)
hummingbird-jp/stat-web pull request #205
Opened 2021-09-23 07:00 UTC by RQ2L84Q-ROW

close #203 

# 1. Orders
メニューの順番をかえて、`Create Your Room`が一番目立つようにした！

# 2. Colors
ボタンの色を変えて、`Create Your Room`が一番目立つようにした！

# 3. Tooltips
- ボタンにカーソルを合わせると、なんとなくの説明が出る
- 文言のわかりやすさはあまり追求できてない！笑

<img width="1437" alt="Screen Shot 2021-09-23 at 14 39 37" src="https://user-images.githubusercontent.com/62736166/134466200-88cb4fb3-f94f-4965-a552-75120dbf3e05.png">

# 4. One more thing...
すでに`Create Your Room`したことがある人が、自分の部屋をさっと選べるようにする実装をはじめた
1.  Firestoreの大元の `users` collection に部屋の情報を追加して（いまは手動）
2. 自分が所属してる部屋をトップ画面に表示

<img width="1440" alt="Screen Shot 2021-09-23 at 15 42 21" src="https://user-images.githubusercontent.com/62736166/134466170-b625f9a8-b089-4820-ae53-df4f52c6193a.png">

2021-09-23 07:02 UTC, RQ2L84Q-ROW commented
@yhakamay PR #204 とコンフリクトすると思うから、あとでいいよ！

2021-09-23 15:05 UTC, yhakamay requested changes

2021-09-23 15:05 UTC, yhakamay commented on dist/index.html
> +							<span class="tooltiptext">
ここがTooltipではなくボタンのラベルとして表示されちゃってるから、修正お願いします！

2021-09-24 00:52 UTC, RQ2L84Q-ROW commented on dist/index.html
> +							<span class="tooltiptext">
ですよね！ありがとう！

2021-09-24 00:58 UTC, RQ2L84Q-ROW commented
@yhakamay チェックお願いしまーす

2021-09-24 01:02 UTC, merged